### ISSUE TITLE
When will the code be released on the RAVDESS and VGGSOUND datasets?

### ISSUE THREAD

**Issue by junwenxiong** [zihuixue/MFH#1]

**Comment by zihuixue** [comment]
Thanks

**Comment by zihuixue** [comment]
Thanks for asking! The plan is to release the code by the end of this month. Will update you once I upload the code.

**Comment by zihuixue** [comment]
Hi @junwenxiong, the code for RAVDESS and VGGSound has been uploaded. Please let me know if there is any further problem!
